# Generated by Django 6.0.6 on 2026-06-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='tfidf', max_length=32)),
                ('test_accuracy', models.FloatField(default=0.0)),
                ('n_train', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artifact_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeferralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tau', models.FloatField(default=0.0)),
                ('system_accuracy', models.FloatField(default=0.0)),
                ('classifier_accuracy', models.FloatField(default=0.0)),
                ('expert_accuracy', models.FloatField(default=0.0)),
                ('coverage', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='project3.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLearningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(default='competence_gap', max_length=32)),
                ('budget', models.IntegerField(default=400)),
                ('final_l1_error', models.FloatField(default=0.0)),
                ('history_json', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_runs', to='project3.trainedmodel')),
            ],
        ),
    ]
