# Generated by Django 5.2.15 on 2026-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSelectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('tree', 'Decision tree'), ('logistic', 'Logistic regression')], max_length=20)),
                ('lam', models.FloatField(help_text='Regularisation lambda at selection time')),
                ('omega', models.FloatField(help_text='Complexity (leaves / non-zero coefs)')),
                ('omega_label', models.CharField(blank=True, max_length=40)),
                ('hyperparam', models.CharField(blank=True, help_text='e.g. "max_leaf_nodes=6" or "C=0.5"', max_length=60)),
                ('acc_test', models.FloatField(help_text='Test accuracy (0-1)')),
                ('acc_train', models.FloatField(help_text='Train accuracy (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
