# Generated by Django 5.2.15 on 2026-09-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('order', models.CharField(choices=[('pairwise_first', 'Pairwise first, then ranking'), ('ranking_first', 'Ranking first, then pairwise')], max_length=20)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('completion_code', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='RankingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.IntegerField()),
                ('movie_ids_json', models.TextField()),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_responses', to='project4.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairwise_difficulty', models.IntegerField()),
                ('ranking_difficulty', models.IntegerField()),
                ('pairwise_confidence', models.IntegerField()),
                ('ranking_confidence', models.IntegerField()),
                ('preferred_method', models.CharField(choices=[('pairwise', 'Pairwise comparisons'), ('ranking', 'Ranking lists'), ('no_preference', 'No preference')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='project4.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='PairwiseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pairwise', 'Elicitation'), ('holdout', 'Holdout')], default='pairwise', max_length=10)),
                ('trial_index', models.IntegerField()),
                ('movie_a', models.IntegerField()),
                ('movie_b', models.IntegerField()),
                ('chosen', models.IntegerField()),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_responses', to='project4.studysession')),
            ],
        ),
    ]
