# Generated by Django 6.0.6 on 2026-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='uploaded dataset', max_length=200)),
                ('model_name', models.CharField(max_length=50)),
                ('problem_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('hyperparameter', models.IntegerField()),
                ('hyperparameter_label', models.CharField(blank=True, max_length=50)),
                ('test_size', models.IntegerField(help_text='Test set size in percent')),
                ('score', models.FloatField()),
                ('score_label', models.CharField(default='Accuracy', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
